version: '3.8'
services:
  excel-mcp-server:
    build: .
    container_name: excel-mcp-server
    ports:
      - "8000:8000"
    environment:
      - EXCEL_FILES_PATH=/app/excel_files
      - FASTMCP_PORT=8000
      - FASTMCP_HOST=0.0.0.0
    volumes:
      - ./excel_files:/app/excel_files
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s 