[phases.setup]
nixPkgs = ["python310", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install uv==$NIXPACKS_UV_VERSION",
  "uv sync --no-dev --frozen"
]

[start]
cmd = "uv run excel-mcp-server streamable-http" 