[build]
builder = "railpack"

[deploy]
startCommand = "uv run excel-mcp-server streamable-http"
healthcheckPath = "/mcp"
healthcheckTimeout = 300

[env]
EXCEL_FILES_PATH = "/app/excel_files"
FASTMCP_PORT = "8000"
FASTMCP_HOST = "0.0.0.0" 