[build]
builder = "railpack"

[deploy]
start = "uv run excel-mcp-server streamable-http"
healthcheck = "/mcp"

[env]
EXCEL_FILES_PATH = "/app/excel_files"
FASTMCP_PORT = "8000"
FASTMCP_HOST = "0.0.0.0" 